In [1]:
import numpy as np
import matplotlib.pyplot as plt
import cv2

In [3]:
img = np.random.randint(20, size = [10,10])

In [4]:
print(img, img.shape)

[[ 4 17 16  3  8 11  0 19 11 13]
 [ 7 17  7  6  4  1  5 12 14 17]
 [13  6  5  6 14 14 16 10  0 10]
 [13 15  4  7  6  8 19  1  0  6]
 [ 4  2  1 16 14  8  4 12 14 18]
 [15 16  7 17  3  1 14 12  0 13]
 [ 3 16  8 18  8 13 11  3 19 18]
 [12 15  9 15 16 11  6  1  6  3]
 [ 0 19 10  5 16 18  9 18  5 12]
 [ 6  8  4  8  2  6  4 13 10  4]] (10, 10)


In [31]:
sz = 3
bd = int(sz / 2)
i, j = 1, 1

In [38]:
sub_img = np.zeros_like(img, dtype='uint8')

In [39]:
m,n = img.shape
t = sz * sz
inx = t // 2
for i in range(bd, m-bd):
    for j in range(bd, n-bd):
        a = img[i-bd : i+bd+1, j-bd : j+bd+1]
        b = np.ravel(a)
        c = np.sort(b)
        sub_img[i, j] = c[inx]
print(sub_img)
        

[[ 0  0  0  0  0  0  0  0  0  0]
 [ 0  7  6  6  7  8 11 11 12  0]
 [ 0  7  6  6  7  8 10 10 10  0]
 [ 0  5  6  6  8 14 10 10 10  0]
 [ 0  7  7  7  8  8  8 12 12  0]
 [ 0  7 16  8 13  8 11 12 13  0]
 [ 0 12 15  9 13 11 11  6  6  0]
 [ 0 10 15 10 15 11 11  6  6  0]
 [ 0  9  9  9 11  9  9  6  6  0]
 [ 0  0  0  0  0  0  0  0  0  0]]
